language: node_js
node_js:
  - "8"

before_script:
  - npm install -g gulp
script: gulp build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: web
  on:
    branch: master
