version: '3.7'

services:
    prod:
      image: sitediff-prod
      container_name: sitediff-prod
      hostname: sitediff-prod
      build:
        context: .
        dockerfile: prod.dockerfile
      ports:
        - 443:443
      restart: always

    dev:
      image: sitediff-dev
      container_name: sitediff-dev
      hostname: sitediff-dev
      build:
        context: .
        dockerfile: dev.dockerfile
      ports:
        - 18180:80
      volumes:
        - ./code:/srv/sitediff.io:cached
